import React, { useState, useEffect } from 'react';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  Tooltip, 
  ResponsiveContainer 
} from 'recharts';
import { 
  ClipboardList, 
  Award, 
  Calendar, 
  Sparkles, 
  Check, 
  Loader2, 
  FileText, 
  CheckCircle,
  TrendingUp
} from 'lucide-react';
import { useToastStore } from '../store/useToastStore';
import { useTheme } from '../utils/theme';
import { useStore } from '../store/useStore';
import { motion, AnimatePresence } from 'framer-motion';
import { jsPDF } from 'jspdf';

export const ESGReports: React.FC = () => {
  const theme = useTheme();
  const { addToast } = useToastStore();
  const { user } = useStore();
  const [period, setPeriod] = useState('Q3 2024');
  const [generating, setGenerating] = useState(false);
  const [genProgress, setGenProgress] = useState(0);
  
  // Checklist states
  const [chk1, setChk1] = useState(true);
  const [chk2, setChk2] = useState(true);
  const [chk3, setChk3] = useState(true);
  const [chk4, setChk4] = useState(true);
  const [chk5, setChk5] = useState(false);

  const complianceData = [
    { month: 'Jan', Target: 30, Actual: 32 },
    { month: 'Feb', Target: 30, Actual: 28 },
    { month: 'Mar', Target: 35, Actual: 38 },
    { month: 'Apr', Target: 35, Actual: 30 },
    { month: 'May', Target: 40, Actual: 45 },
    { month: 'Jun', Target: 40, Actual: 42 },
    { month: 'Jul', Target: 45, Actual: 40 },
    { month: 'Aug', Target: 45, Actual: 46 },
    { month: 'Sep', Target: 50, Actual: 48 },
    { month: 'Oct', Target: 50, Actual: 52 },
    { month: 'Nov', Target: 55, Actual: 50 },
    { month: 'Dec', Target: 55, Actual: 58 },
  ];

  // Dynamic bar coloring function based on compliance performance
  const renderCustomBar = (props: any) => {
    const { x, y, width, height, Target, Actual } = props;
    const ratio = Actual / Target;
    let fill = '#10B981'; // Green (>=100% compliance)
    if (ratio < 0.8) fill = '#EF4444'; // Red (<80% compliance)
    else if (ratio < 1.0) fill = '#F59E0B'; // Amber (80-100% compliance)
    
    return <rect x={x} y={y} width={width} height={height} fill={fill} rx={3} />;
  };

  const downloadESGReportAsPDF = () => {
    try {
      const complianceRatio = Math.min(100, Math.round((250 / 500) * 100));

      // Portrait A4 (210mm x 297mm)
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      // 1. Draw Background (Void color #080C14)
      doc.setFillColor(8, 12, 20);
      doc.rect(0, 0, 210, 297, 'F');

      // 2. Draw Borders (Green color #00E5A0)
      doc.setDrawColor(0, 229, 160);
      doc.setLineWidth(0.5);
      doc.rect(10, 10, 190, 277, 'S');

      // 3. Header
      doc.setTextColor(0, 229, 160);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('ACCN ESG CARBON COMPLIANCE', 20, 25);

      doc.setTextColor(160, 174, 192);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text('Generated by ACCN AI Audit Engine', 20, 31);

      // Period Badge
      doc.setFillColor(26, 34, 53);
      doc.setDrawColor(0, 229, 160);
      doc.setLineWidth(0.2);
      doc.rect(150, 18, 40, 10, 'FD');
      doc.setTextColor(0, 229, 160);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text(`${period} REPORT`, 170, 24, { align: 'center' });

      // 4. Meta Details Section
      doc.setFillColor(26, 34, 53); // nebula bg
      doc.rect(20, 40, 170, 45, 'F');
      
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);

      // Row 1
      doc.setTextColor(113, 128, 150);
      doc.text('ORGANIZATION MEMBER', 25, 48);
      doc.text('LOCATION JURISDICTION', 110, 48);
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.text(user.name, 25, 54);
      doc.text(user.location, 110, 54);

      // Row 2
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(113, 128, 150);
      doc.text('ACCOUNT EMAIL', 25, 68);
      doc.text('AUDIT STATUS', 110, 68);
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.text(user.email, 25, 74);
      doc.text('ACTIVE / SIGNED BY ARIA AI', 110, 74);

      // 5. Stats boxes
      doc.setFillColor(20, 30, 45);
      // Box 1
      doc.rect(20, 95, 50, 30, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('250 Tons', 45, 110, { align: 'center' });
      doc.setTextColor(113, 128, 150);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.text('CO2 OFFSET SAVED', 45, 118, { align: 'center' });

      // Box 2
      doc.setFillColor(20, 30, 45);
      doc.rect(80, 95, 50, 30, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('500 Tons', 105, 110, { align: 'center' });
      doc.setTextColor(113, 128, 150);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.text('QUARTERLY TARGET', 105, 118, { align: 'center' });

      // Box 3
      doc.setFillColor(20, 30, 45);
      doc.rect(140, 95, 50, 30, 'F');
      doc.setTextColor(0, 229, 160);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('94%', 165, 110, { align: 'center' });
      doc.setTextColor(113, 128, 150);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.text('COMPLIANCE SCORE', 165, 118, { align: 'center' });

      // 6. Verification Text Box
      doc.setDrawColor(61, 110, 255); // ion border
      doc.setFillColor(15, 25, 45);
      doc.setLineWidth(0.2);
      doc.rect(20, 140, 170, 35, 'FD');

      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text('Cryptographic Audit Statement:', 25, 148);

      doc.setTextColor(160, 174, 192);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      const splitText = doc.splitTextToSize(
        `This document serves as verification that the registered smart grids paired to owner ${user.name} have successfully verified 250 Tons of CO2 reduction against a target benchmark of 500 Tons. Telemetry feeds have been verified using ARIA AI audit logs with a reliability match of ${user.trustScore}%.`,
        160
      );
      doc.text(splitText, 25, 156);

      // 7. Footer
      doc.setDrawColor(30, 41, 59);
      doc.setLineWidth(0.3);
      doc.line(20, 250, 190, 250);

      doc.setTextColor(0, 229, 160);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text('✓ VERIFIED BY ARIA AI', 20, 260);
      doc.setTextColor(113, 128, 150);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.text('ACCN Compliance Protocol V3.0', 20, 265);

      doc.text(`REPORT ID: ACCN-ESG-${period.replace(' ', '-')}-${Date.now().toString().slice(-5)}`, 190, 260, { align: 'right' });
      doc.text('SHA-256 SIGNATURE: a8b2f9011de54f8287c118b', 190, 265, { align: 'right' });

      // Save PDF file directly (triggers immediate download)
      const fileName = `ESG_Carbon_Report_${period.replace(' ', '_')}.pdf`;
      doc.save(fileName);
      addToast('success', 'PDF Saved', `${fileName} downloaded successfully.`);
    } catch (err) {
      console.error('Failed to generate ESG PDF:', err);
      addToast('error', 'PDF Generation Failed', 'Unable to create PDF file.');
    }
  };

  const handleGenerateReport = () => {
    // Download synchronously inside the click handler to prevent Safari from blocking it
    downloadESGReportAsPDF();
    
    // Trigger visual compile animation
    setGenerating(true);
    setGenProgress(0);
  };

  useEffect(() => {
    if (!generating) return;

    const timer = setInterval(() => {
      setGenProgress((p) => {
        if (p >= 100) {
          clearInterval(timer);
          setTimeout(() => {
            setGenerating(false);
          }, 300);
          return 100;
        }
        return p + 4;
      });
    }, 80);

    return () => clearInterval(timer);
  }, [generating]);

  return (
    <div className="flex flex-col gap-6 w-full pb-12 select-none">
      {/* Top Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-cardBorder pb-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-cardBorder flex items-center justify-center border border-white/5 font-bold text-xs text-textSecondary">
            🏢
          </div>
          <div>
            <h1 className="text-2xl md:text-3xl font-bold font-heading text-white">ESG Carbon Compliance</h1>
            <p className="text-xs text-textSecondary mt-0.5">Corporate compliance ratings and carbon targets audit.</p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <select
            value={period}
            onChange={(e) => setPeriod(e.target.value)}
            className="px-3.5 py-2.5 rounded-xl bg-cardSurface/60 border border-cardBorder text-xs text-textPrimary focus:outline-none"
          >
            <option value="Q1 2024">Q1 2024</option>
            <option value="Q2 2024">Q2 2024</option>
            <option value="Q3 2024">Q3 2024</option>
            <option value="Q4 2024">Q4 2024</option>
          </select>

          <button
            onClick={handleGenerateReport}
            className="px-5 py-2.5 rounded-xl bg-accentGreen text-bgSpace text-xs font-bold hover:scale-102 transition-transform shadow-neon-green flex items-center gap-1.5"
          >
            <ClipboardList className="w-4 h-4" />
            Generate PDF
          </button>
        </div>
      </div>

      {/* Top Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-5 rounded-2xl border border-cardBorder bg-cardSurface/40 flex flex-col gap-2 glass-panel">
          <span className="text-[10px] font-mono text-textMuted uppercase select-none">Carbon Offset</span>
          <span className="text-2xl font-bold font-mono text-white">250 Tons</span>
          <span className="text-[10px] text-accentGreen font-bold font-mono flex items-center gap-1">
            ✓ On Track
          </span>
        </div>

        <div className="p-5 rounded-2xl border border-cardBorder bg-cardSurface/40 flex flex-col gap-2 glass-panel">
          <span className="text-[10px] font-mono text-textMuted uppercase select-none">Credits Purchased</span>
          <span className="text-2xl font-bold font-mono text-white">2,083 Credits</span>
          <span className="text-[10px] text-accentGreen font-bold font-mono flex items-center gap-1">
            &uarr; +120 this month
          </span>
        </div>

        <div className="p-5 rounded-2xl border border-cardBorder bg-cardSurface/40 flex flex-col gap-2 glass-panel">
          <span className="text-[10px] font-mono text-textMuted uppercase select-none">ESG Target</span>
          <span className="text-2xl font-bold font-mono text-white">500 Tons</span>
          <span className="text-[10px] text-accentCyan font-bold font-mono flex items-center gap-1">
            50% Achieved
          </span>
        </div>

        <div className="p-5 rounded-2xl border border-cardBorder bg-cardSurface/40 flex flex-col gap-2 glass-panel">
          <span className="text-[10px] font-mono text-textMuted uppercase select-none">Compliance Score</span>
          <span className="text-2xl font-bold font-mono text-white">94%</span>
          <span className="text-[10px] text-accentPurple font-bold font-mono flex items-center gap-1">
            A+ Rating
          </span>
        </div>
      </div>

      {/* Compliance Chart & Progress Rings */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Compliance Bar Chart (Recharts) */}
        <div className="lg:col-span-2 p-5 rounded-2xl border border-cardBorder bg-cardSurface/40 flex flex-col gap-5 glass-panel">
          <div className="flex justify-between items-center select-none">
            <div>
              <h3 className="text-sm font-bold text-white uppercase tracking-wider font-heading">
                Monthly Offset Mandate
              </h3>
              <span className="text-[9px] text-textSecondary">
                Target vs Actual emissions offset (Red: under compliant, Green: fully compliant)
              </span>
            </div>
            {/* Small animated progress circle */}
            <div className="w-12 h-12 relative flex items-center justify-center">
              <svg className="w-full h-full transform -rotate-90">
                <circle cx="24" cy="24" r="18" stroke="#1e2d45" strokeWidth="2.5" fill="none" />
                <circle cx="24" cy="24" r="18" stroke="#7C3AED" strokeWidth="3" strokeDasharray={2*Math.PI*18} strokeDashoffset={(2*Math.PI*18)*0.06} fill="none" strokeLinecap="round" />
              </svg>
              <span className="absolute text-[9px] font-mono font-bold text-accentPurple">94%</span>
            </div>
          </div>

          <div className="w-full h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={complianceData} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}>
                <XAxis dataKey="month" stroke="#475569" fontSize={9} fontFamily="monospace" tickLine={false} />
                <YAxis stroke="#475569" fontSize={9} fontFamily="monospace" tickLine={false} axisLine={false} />
                <Tooltip
                  contentStyle={{
                    backgroundColor: '#111827',
                    border: '1px solid #1E2D45',
                    borderRadius: '12px',
                    color: '#F1F5F9',
                    fontSize: '10px',
                    fontFamily: 'monospace'
                  }}
                />
                {/* Target line bar representing boundary limits */}
                <Bar dataKey="Target" fill="none" stroke="#475569" strokeDasharray="3 3" strokeWidth={1} radius={[3, 3, 0, 0]} />
                {/* Actual carbon offset */}
                <Bar dataKey="Actual" shape={renderCustomBar} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Progress Rings column */}
        <div className="p-5 rounded-2xl border border-cardBorder bg-cardSurface/40 flex flex-col gap-6 glass-panel justify-center items-center">
          <h3 className="text-xs font-bold text-white uppercase tracking-wider font-mono self-start border-b border-cardBorder pb-2 w-full select-none">
            Annual ESG Benchmark Target
          </h3>

          <div className="flex flex-col gap-4 w-full">
            {/* Ring 1: Carbon Offset */}
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 relative flex items-center justify-center flex-shrink-0">
                <svg className="w-full h-full transform -rotate-90">
                  <circle cx="28" cy="28" r="22" stroke="#1e2d45" strokeWidth="3.5" fill="none" />
                  <circle cx="28" cy="28" r="22" stroke="#00FF88" strokeWidth="4.5" strokeDasharray={2*Math.PI*22} strokeDashoffset={(2*Math.PI*22)*0.5} fill="none" strokeLinecap="round" />
                </svg>
                <span className="absolute text-[10px] font-mono font-bold text-accentGreen">50%</span>
              </div>
              <div className="flex flex-col">
                <span className="text-xs font-bold text-white leading-none">Carbon Offset Volume</span>
                <span className="text-[10px] text-textSecondary mt-1 select-none">250 Tons offset of 500 Tons target</span>
              </div>
            </div>

            {/* Ring 2: Credits Purchased */}
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 relative flex items-center justify-center flex-shrink-0">
                <svg className="w-full h-full transform -rotate-90">
                  <circle cx="28" cy="28" r="22" stroke="#1e2d45" strokeWidth="3.5" fill="none" />
                  <circle cx="28" cy="28" r="22" stroke="#00D4FF" strokeWidth="4.5" strokeDasharray={2*Math.PI*22} strokeDashoffset={(2*Math.PI*22)*0.17} fill="none" strokeLinecap="round" />
                </svg>
                <span className="absolute text-[10px] font-mono font-bold text-accentCyan">83%</span>
              </div>
              <div className="flex flex-col">
                <span className="text-xs font-bold text-white leading-none">Credits Acquired Target</span>
                <span className="text-[10px] text-textSecondary mt-1 select-none">2,083 CR purchased of 2,500 target</span>
              </div>
            </div>

            {/* Ring 3: Emissions Reduced */}
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 relative flex items-center justify-center flex-shrink-0">
                <svg className="w-full h-full transform -rotate-90">
                  <circle cx="28" cy="28" r="22" stroke="#1e2d45" strokeWidth="3.5" fill="none" />
                  <circle cx="28" cy="28" r="22" stroke="#7C3AED" strokeWidth="4.5" strokeDasharray={2*Math.PI*22} strokeDashoffset={(2*Math.PI*22)*0.33} fill="none" strokeLinecap="round" />
                </svg>
                <span className="absolute text-[10px] font-mono font-bold text-accentPurple">67%</span>
              </div>
              <div className="flex flex-col">
                <span className="text-xs font-bold text-white leading-none">Emissions Reduced Ratio</span>
                <span className="text-[10px] text-textSecondary mt-1 select-none">67% raw carbon offset efficiency achieved</span>
              </div>
            </div>
          </div>
        </div>

      </div>

      {/* PDF Report compiler checklist */}
      <div className="p-6 rounded-2xl border border-cardBorder bg-cardSurface/40 glass-panel max-w-xl">
        <h3 className="text-sm font-bold text-white font-heading mb-4 select-none">
          PDF Report Compiler Options
        </h3>

        <div className="flex flex-col gap-3 font-mono text-xs">
          <label className="flex items-center gap-3 text-textSecondary hover:text-textPrimary cursor-pointer">
            <input
              type="checkbox"
              checked={chk1}
              onChange={() => setChk1(!chk1)}
              className="rounded border-cardBorder text-accentGreen focus:ring-accentGreen bg-bgSpace cursor-pointer w-4.5 h-4.5"
            />
            [✓] Executive Carbon Summary Overview
          </label>
          <label className="flex items-center gap-3 text-textSecondary hover:text-textPrimary cursor-pointer">
            <input
              type="checkbox"
              checked={chk2}
              onChange={() => setChk2(!chk2)}
              className="rounded border-cardBorder text-accentGreen focus:ring-accentGreen bg-bgSpace cursor-pointer w-4.5 h-4.5"
            />
            [✓] Carbon Credit Transactions Ledgers
          </label>
          <label className="flex items-center gap-3 text-textSecondary hover:text-textPrimary cursor-pointer">
            <input
              type="checkbox"
              checked={chk3}
              onChange={() => setChk3(!chk3)}
              className="rounded border-cardBorder text-accentGreen focus:ring-accentGreen bg-bgSpace cursor-pointer w-4.5 h-4.5"
            />
            [✓] Monthly Compliance Performance Charts
          </label>
          <label className="flex items-center gap-3 text-textSecondary hover:text-textPrimary cursor-pointer">
            <input
              type="checkbox"
              checked={chk4}
              onChange={() => setChk4(!chk4)}
              className="rounded border-cardBorder text-accentGreen focus:ring-accentGreen bg-bgSpace cursor-pointer w-4.5 h-4.5"
            />
            [✓] Cryptographic AI Verification Signatures
          </label>
          <label className="flex items-center gap-3 text-textSecondary hover:text-textPrimary cursor-pointer">
            <input
              type="checkbox"
              checked={chk5}
              onChange={() => setChk5(!chk5)}
              className="rounded border-cardBorder text-accentGreen focus:ring-accentGreen bg-bgSpace cursor-pointer w-4.5 h-4.5"
            />
            [ ] Raw Energy Telemetry Export Details
          </label>
        </div>

        {/* Generate Report Progress */}
        <AnimatePresence>
          {generating && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="mt-6 flex flex-col gap-2 font-mono text-[10px]"
            >
              <div className="flex justify-between text-accentCyan">
                <span className="flex items-center gap-1.5 font-bold animate-pulse">
                  <Loader2 className="w-3.5 h-3.5 animate-spin" /> Compiling report...
                </span>
                <span>{genProgress}%</span>
              </div>
              <div className="w-full h-1 bg-cardBorder rounded-full overflow-hidden">
                <div className="h-full bg-accentCyan shadow-neon-cyan transition-all" style={{ width: `${genProgress}%` }} />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <button
          onClick={handleGenerateReport}
          disabled={generating}
          className="w-full mt-6 py-3 rounded-xl bg-accentGreen text-bgSpace text-xs font-bold hover:scale-102 active:scale-[0.98] transition-all flex items-center justify-center gap-1.5 shadow-neon-green disabled:opacity-50 disabled:pointer-events-none"
        >
          {generating ? 'Processing PDF Compile...' : 'Download PDF Report'}
        </button>
      </div>

    </div>
  );
};
